### ISSUE TITLE
Support for Linux

### ISSUE THREAD

**Issue by eugenechyrski** [letterassist-ai/flusseract#1]
Thanks for the efforts! are there any plans to support building app for linux as well? Looks like the shared  library currently does not support native platforms other than mac

**Comment by mevansam** [comment]
Yes I have plans to support Linux and Windows. Should have it done sometime in the next couple of weeks time permitting.

**Comment by jpdup** [comment]
I have a flutter app using **flusseract**, it builds and run perfectly on MacOS (Intel).
However when attempting to build the same app on Ubuntu the build fails while trying to build Tessaract

The logs starts with an odd mention of "Android SDK not found"

`/home/jp/src/github/MoneyFlutter/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[   +4 ms] [  +50 ms] Unable to locate an Android SDK.
[        ] [  +17 ms] executing: uname -m
[        ] [  +23 ms] Exit code 0 from: uname -m
[        ] [        ] x86_64
[        ] [ +162 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] [   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [   +4 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [   +4 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [ +540 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +2 ms] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [   +4 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [ +235 ms] Initializing file store
[        ] [  +67 ms] Done initializing file store
[        ] [ +251 ms] Skipping target: gen_localizations
[        ] [  +25 ms] Skipping target: gen_dart_plugin_registrant
[        ] [ +981 ms] Skipping target: unpack_linux
[        ] [+1033 ms] Skipping target: kernel_snapshot_program
[        ] [   +5 ms] Skipping target: native_assets
[        ] [        ] Skipping target: kernel_snapshot_native_assets
[        ] [        ] Skipping target: kernel_snapshot
[        ] [  +10 ms] invalidated build due to missing files: /home/jp/src/github/MoneyFlutter/DOES_NOT_EXIST_RERUN_FOR_WILDCARD424168304
[        ] [+1466 ms] debug_bundle_linux-x64_assets: Starting due to {InvalidatedReasonKind.inputMissing: The following inputs were missing:
/home/jp/src/github/MoneyFlutter/DOES_NOT_EXIST_RERUN_FOR_WILDCARD424168304}
[   +2 ms] [ +731 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[        ] [ +216 ms] shaderc command: [/usr/bin/flutter/bin/cache/artifacts/engine/linux-x64/impellerc, --sksl, --runtime-stage-gles, --runtime-stage-vulkan, --iplr,
--sl=/home/jp/src/github/MoneyFlutter/build/flutter_assets/shaders/ink_sparkle.frag, --spirv=/home/jp/src/github/MoneyFlutter/build/flutter_assets/shaders/ink_sparkle.frag.spirv,
--input=/usr/bin/flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag, --input-type=frag, --include=/usr/bin/flutter/packages/flutter/lib/src/material/shaders,
--include=/usr/bin/flutter/bin/cache/artifacts/engine/linux-x64/shader_lib]
[        ] [ +851 ms] debug_bundle_linux-x64_assets: Complete
[        ] [ +642 ms] Persisting file store
[        ] [  +28 ms] Done persisting file store
[        ] [  +57 ms] build succeeded.
[        ] [  +14 ms] "flutter assemble" took 7,243ms.
[        ] [ +141 ms] ensureAnalyticsSent: 119ms
[        ] [        ] Running 1 shutdown hook
[        ] [        ] Shutdown hooks complete
[        ] [   +8 ms] exiting with code 0
[        ] ninja: build stopped: subcommand failed.
[  +23 ms] Building Linux application... (completed in 12.0s)
[+5473 ms] Error: Build process failed
[   +1 ms] "flutter run" took 21,651ms.
[   +7 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:874:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>`
